### ISSUE TITLE
Feature Request: Please add support for more currencies (USD + GBP)

### ISSUE THREAD

**Issue by GuybrushX** [willuhn/hibiscus.transferwise#1]
Thank you very much for the plugin. It's working fine with my tested EUR account (followed instructions here: https://www.willuhn.de/blog/index.php?/archives/835-Hibiscus-Support-fuer-Transferwise.html)

As you mentioned on your site already only EUR is supported.

I would be interested in additional currencies, mainly USD + GBP. Not sure if multi-currency is supported generally but the numbers only without any conversion is fine for my usecase. To see totals in EUR would be nice though.

If necessary I can provide you read-only access to an account for testing with a few transactions.

**Comment by willuhn** [comment]
Hibiscus itself doesnt support multiple currencies. Sorry.
